### ISSUE TITLE
Jekyll blog howto links broken

### ISSUE THREAD

**Issue by mintyc** [rplopes/ricardolopes.net#1]
Part 2 and 3 dont look like they are served correctly.
Reading from android mobile.

Very nice set of posts though. Read the .md files

**Comment by mintyc** [comment]
Also several other blog posts such as the ruby rails ones. Other posts working ok.

**Comment by rplopes** [comment]
Thank you for warning. I thought I had fixed the broken links (problem with upgrading from jekyll 2 to 3), but apparently I haven't. Oh the irony.

**Comment by rplopes** [comment]
Fixed. The server wasn't 100% in sync with the repo, so that's why only some blog posts were missing. Good to know this.

Thank you for alerting me of this issue. And glad you liked the posts :+1:
